"""add appointment lifecycle fields

Revision ID: 08e5703e27f9
Revises: ccdf7ededccc
Create Date: 2026-09-28 19:43:05.601708

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08e5703e27f9"
down_revision: str | Sequence[str] | None = "ccdf7ededccc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("appointments", sa.Column("has_other_professional_nails", sa.Boolean(), nullable=False))
    op.add_column("appointments", sa.Column("deposit_paid_at", sa.DateTime(), nullable=True))
    op.add_column("appointments", sa.Column("attendance_confirmed_at", sa.DateTime(), nullable=True))
    op.add_column("appointments", sa.Column("reminder_sent_at", sa.DateTime(), nullable=True))
    op.add_column("appointments", sa.Column("cancelled_at", sa.DateTime(), nullable=True))
    op.add_column(
        "appointments",
        sa.Column(
            "cancellation_reason",
            sa.Enum("CLIENT_EARLY", "CLIENT_LATE", "NOT_CONFIRMED", "BY_STUDIO", name="cancellationreason"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("appointments", "cancellation_reason")
    op.drop_column("appointments", "cancelled_at")
    op.drop_column("appointments", "reminder_sent_at")
    op.drop_column("appointments", "attendance_confirmed_at")
    op.drop_column("appointments", "deposit_paid_at")
    op.drop_column("appointments", "has_other_professional_nails")
    # ### end Alembic commands ###
