"""add prices and policies

Revision ID: 1305a046db5d
Revises: e24a4eca5140
Create Date: 2026-09-28 02:39:16.163759

"""

from collections.abc import Sequence
from decimal import Decimal

import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlmodel import AutoString

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1305a046db5d"
down_revision: str | Sequence[str] | None = "e24a4eca5140"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    addon_prices = op.create_table(
        "addon_prices",
        sa.Column("addon", sa.Enum("BROKEN_NAIL", "EXTRA_CHARM", name="addon"), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("addon"),
    )
    nail_art_prices = op.create_table(
        "nail_art_prices",
        sa.Column(
            "nail_art_level",
            sa.Enum("LEVEL_1", "LEVEL_2", "LEVEL_3", name="nailartlevel"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("nail_art_level"),
    )
    op.create_table(
        "policies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", AutoString(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "published_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version", name="uc_policies_version"),
    )
    service_prices = op.create_table(
        "service_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "service",
            sa.Enum("APPLICATION", "MAINTENANCE", "REMOVAL", name="service"),
            nullable=False,
        ),
        sa.Column(
            "nail_size",
            sa.Enum("SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE", name="nailsize"),
            nullable=True,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("service", "nail_size", name="uc_service_prices_service_size"),
    )
    op.alter_column(
        "appointments",
        "service",
        existing_type=mysql.ENUM("APPLICATION", "MAINTENANCE", "REMOVAL", "REMOVAL_MANICURE"),
        type_=sa.Enum("APPLICATION", "MAINTENANCE", "REMOVAL", name="service"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        service_prices,
        [
            {
                "service": "APPLICATION",
                "nail_size": "SMALL",
                "amount": Decimal("35.00"),
            },
            {
                "service": "APPLICATION",
                "nail_size": "MEDIUM",
                "amount": Decimal("40.00"),
            },
            {
                "service": "APPLICATION",
                "nail_size": "LARGE",
                "amount": Decimal("45.00"),
            },
            {
                "service": "APPLICATION",
                "nail_size": "XLARGE",
                "amount": Decimal("50.00"),
            },
            {
                "service": "APPLICATION",
                "nail_size": "XXLARGE",
                "amount": Decimal("55.00"),
            },
            {
                "service": "MAINTENANCE",
                "nail_size": "SMALL",
                "amount": Decimal("30.00"),
            },
            {
                "service": "MAINTENANCE",
                "nail_size": "MEDIUM",
                "amount": Decimal("35.00"),
            },
            {
                "service": "MAINTENANCE",
                "nail_size": "LARGE",
                "amount": Decimal("40.00"),
            },
            {
                "service": "MAINTENANCE",
                "nail_size": "XLARGE",
                "amount": Decimal("45.00"),
            },
            {
                "service": "MAINTENANCE",
                "nail_size": "XXLARGE",
                "amount": Decimal("50.00"),
            },
            {"service": "REMOVAL", "nail_size": None, "amount": Decimal("10.00")},
        ],
    )
    op.bulk_insert(
        nail_art_prices,
        [
            {"nail_art_level": "LEVEL_1", "amount": Decimal("4.00")},
            {"nail_art_level": "LEVEL_2", "amount": Decimal("8.00")},
            {"nail_art_level": "LEVEL_3", "amount": Decimal("12.00")},
        ],
    )
    op.bulk_insert(
        addon_prices,
        [
            {"addon": "BROKEN_NAIL", "amount": Decimal("1.50")},
            {"addon": "EXTRA_CHARM", "amount": Decimal("0.50")},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "appointments",
        "service",
        existing_type=sa.Enum("APPLICATION", "MAINTENANCE", "REMOVAL", name="service"),
        type_=mysql.ENUM("APPLICATION", "MAINTENANCE", "REMOVAL", "REMOVAL_MANICURE"),
        existing_nullable=False,
    )
    op.drop_table("service_prices")
    op.drop_table("policies")
    op.drop_table("nail_art_prices")
    op.drop_table("addon_prices")
    # ### end Alembic commands ###
