"""move phone to users and add pre approved instagrams

Revision ID: 2a2275840b5a
Revises: dba419e35d30
Create Date: 2026-09-25 20:19:49.856926

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlmodel import AutoString

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a2275840b5a"
down_revision: str | Sequence[str] | None = "dba419e35d30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pre_approved_instagrams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instagram", AutoString(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instagram", name="uc_pre_approved_instagram"),
    )
    op.drop_index(op.f("ix_phone_numbers_phone_hash"), table_name="phone_numbers")
    op.drop_index(op.f("uc_phone_numbers_phone_hash"), table_name="phone_numbers")
    op.drop_table("phone_numbers")
    op.alter_column(
        "appointments",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "appointments",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.drop_index(op.f("user_id"), table_name="user_profiles")
    op.add_column("users", sa.Column("phone_encrypted", AutoString(length=512), nullable=False))
    op.add_column("users", sa.Column("phone_hash", AutoString(length=64), nullable=False))
    op.alter_column("users", "password_hash", existing_type=mysql.VARCHAR(length=255), nullable=True)
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_users_email_hash"), table_name="users")
    op.create_unique_constraint("uc_users_instagram", "users", ["instagram"])
    op.create_unique_constraint("uc_users_phone_hash", "users", ["phone_hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uc_users_phone_hash", "users", type_="unique")
    op.drop_constraint("uc_users_instagram", "users", type_="unique")
    op.create_index(op.f("ix_users_email_hash"), "users", ["email_hash"], unique=False)
    op.alter_column("users", "updated_at", existing_type=mysql.DATETIME(), server_default=None, existing_nullable=False)
    op.alter_column("users", "created_at", existing_type=mysql.DATETIME(), server_default=None, existing_nullable=False)
    op.alter_column("users", "password_hash", existing_type=mysql.VARCHAR(length=255), nullable=False)
    op.drop_column("users", "phone_hash")
    op.drop_column("users", "phone_encrypted")
    op.create_index(op.f("user_id"), "user_profiles", ["user_id"], unique=True)
    op.alter_column(
        "appointments", "updated_at", existing_type=mysql.DATETIME(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "appointments", "created_at", existing_type=mysql.DATETIME(), server_default=None, existing_nullable=False
    )
    op.create_table(
        "phone_numbers",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("phone_encrypted", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("phone_hash", mysql.VARCHAR(length=64), nullable=False),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("phone_numbers_ibfk_1"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("uc_phone_numbers_phone_hash"), "phone_numbers", ["phone_hash"], unique=True)
    op.create_index(op.f("ix_phone_numbers_phone_hash"), "phone_numbers", ["phone_hash"], unique=False)
    op.drop_table("pre_approved_instagrams")
    # ### end Alembic commands ###
