"""add audit for cancelled apointments

Revision ID: 64a10f560aa6
Revises: 08e5703e27f9
Create Date: 2026-09-29 19:18:17.805899

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64a10f560aa6"
down_revision: str | Sequence[str] | None = "08e5703e27f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("appointments", sa.Column("cancelled_by", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_appointments_cancelled_by", "appointments", "users", ["cancelled_by"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_appointments_cancelled_by", "appointments", type_="foreignkey")
    op.drop_column("appointments", "cancelled_by")
    # ### end Alembic commands ###
