"""add agenda tables and revise appointments

Revision ID: ccdf7ededccc
Revises: 1305a046db5d
Create Date: 2026-09-28 02:52:13.344998

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccdf7ededccc"
down_revision: str | Sequence[str] | None = "1305a046db5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "published_months",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint("year", "month"),
    )
    op.create_table(
        "schedule_exceptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("slot_time", sa.Time(), nullable=True),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("day", "slot_time", name="uc_schedule_exceptions_day_slot"),
    )
    op.create_index(op.f("ix_schedule_exceptions_day"), "schedule_exceptions", ["day"], unique=False)
    op.create_table(
        "booked_slots",
        sa.Column("slot_at", sa.DateTime(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["appointment_id"], ["appointments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("slot_at"),
    )
    op.create_index(op.f("ix_booked_slots_appointment_id"), "booked_slots", ["appointment_id"], unique=False)
    op.add_column(
        "appointments",
        sa.Column("nail_art_level", sa.Enum("LEVEL_1", "LEVEL_2", "LEVEL_3", name="nailartlevel"), nullable=True),
    )
    op.add_column("appointments", sa.Column("broken_nails", sa.Integer(), nullable=False))
    op.add_column("appointments", sa.Column("estimated_price", sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column("appointments", sa.Column("policy_id", sa.Integer(), nullable=False))
    op.add_column("appointments", sa.Column("policies_accepted_at", sa.DateTime(), nullable=False))
    op.alter_column("appointments", "final_price", existing_type=mysql.DECIMAL(precision=10, scale=2), nullable=True)
    op.drop_index(op.f("uc_appointments_schedule_at"), table_name="appointments")
    op.create_index(op.f("ix_appointments_scheduled_at"), "appointments", ["scheduled_at"], unique=False)
    op.create_foreign_key(
        "fk_appointments_policy_id", "appointments", "policies", ["policy_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_column("appointments", "is_deposit_paid")
    op.add_column("users", sa.Column("wants_agenda_emails", sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column(
        "users", "wants_agenda_emails", existing_type=sa.Boolean(), existing_nullable=False, server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "wants_agenda_emails")
    op.add_column(
        "appointments",
        sa.Column(
            "is_deposit_paid",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.drop_constraint("fk_appointments_policy_id", "appointments", type_="foreignkey")
    op.drop_index(op.f("ix_appointments_scheduled_at"), table_name="appointments")
    op.create_index(op.f("uc_appointments_schedule_at"), "appointments", ["scheduled_at"], unique=True)
    op.alter_column("appointments", "final_price", existing_type=mysql.DECIMAL(precision=10, scale=2), nullable=False)
    op.drop_column("appointments", "policies_accepted_at")
    op.drop_column("appointments", "policy_id")
    op.drop_column("appointments", "estimated_price")
    op.drop_column("appointments", "broken_nails")
    op.drop_column("appointments", "nail_art_level")
    op.drop_table("booked_slots")
    op.drop_table("schedule_exceptions")
    op.drop_table("published_months")
    # ### end Alembic commands ###
