"""create initial scheduling tables

Revision ID: dba419e35d30
Revises:
Create Date: 2026-09-24 20:50:55.078069

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlmodel import AutoString

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dba419e35d30"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instagram", AutoString(length=255), nullable=True),
        sa.Column("name", AutoString(length=255), nullable=False),
        sa.Column("last_name", AutoString(length=255), nullable=False),
        sa.Column("email_encrypted", AutoString(length=512), nullable=False),
        sa.Column("email_hash", AutoString(length=64), nullable=False),
        sa.Column("role", sa.Enum("USER", "SUPER_ADMIN", name="userrole"), nullable=False),
        sa.Column("password_hash", AutoString(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_hash", name="uc_users_email_hash"),
    )
    op.create_index(op.f("ix_users_email_hash"), "users", ["email_hash"], unique=False)
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column("is_deposit_paid", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SCHEDULED", "CONFIRMED", "COMPLETED", "CANCELLED", "NO_SHOW", name="appointmentstatus"),
            nullable=False,
        ),
        sa.Column(
            "service",
            sa.Enum("APPLICATION", "MAINTENANCE", "REMOVAL", "REMOVAL_MANICURE", name="service"),
            nullable=False,
        ),
        sa.Column(
            "nail_size", sa.Enum("SMALL", "MEDIUM", "LARGE", "XLARGE", "XXLARGE", name="nailsize"), nullable=True
        ),
        sa.Column("final_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scheduled_at", name="uc_appointments_schedule_at"),
    )
    op.create_table(
        "phone_numbers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone_encrypted", AutoString(), nullable=False),
        sa.Column("phone_hash", AutoString(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_hash", name="uc_phone_numbers_phone_hash"),
    )
    op.create_index(op.f("ix_phone_numbers_phone_hash"), "phone_numbers", ["phone_hash"], unique=False)
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("nail_type", AutoString(length=255), nullable=True),
        sa.Column("cuticle_type", AutoString(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("appointment_frequency_weeks", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_phone_numbers_phone_hash"), table_name="phone_numbers")
    op.drop_table("phone_numbers")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_users_email_hash"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
