"""add verification codes and email verified

Revision ID: e24a4eca5140
Revises: 2a2275840b5a
Create Date: 2026-09-25 21:35:51.559775

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlmodel import AutoString

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e24a4eca5140"
down_revision: str | Sequence[str] | None = "2a2275840b5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.Enum("CHECKIN", "ACTIVATION", name="verificationpurpose"), nullable=False),
        sa.Column("code_hash", AutoString(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "purpose", name="uc_verification_codes_user_purpose"),
    )
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.execute("UPDATE users SET email_verified = 1 WHERE role = 'SUPER_ADMIN'")
    op.alter_column("users", "email_verified", existing_type=sa.Boolean(), existing_nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified")
    op.drop_table("verification_codes")
    # ### end Alembic commands ###
